---
version: "3.8"

services:
  nautobot:
    environment:
      - "NAUTOBOT_DB_ENGINE=django.db.backends.postgresql"
  db:
    image: "postgres:13-alpine"
    env_file:
      - "development.env"
      - "creds.env"
    volumes:
      # - "./nautobot.sql:/tmp/nautobot.sql"
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"
      interval: "10s"
      timeout: "5s"
      retries: 10

volumes:
  postgres_data: {}
