# Generated by Django 3.1.3 on 2021-02-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0001_initial"),
    ]

    def insertData(apps, schema_editor):
        GoldenConfigSettings = apps.get_model("nautobot_golden_config", "GoldenConfigSettings")
        global_settings = GoldenConfigSettings.objects.create(id="aaaaaaaa-0000-0000-0000-000000000001")
        global_settings.save()

    operations = [
        migrations.RunPython(insertData),
    ]
