# Generated by Django 3.1.7 on 2021-04-13 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_golden_config', '0002_custom_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenConfigLineSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('line_update_type', models.TextField(blank=True)),
                ('regex_line', models.TextField(blank=True)),
                ('substitute_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
