# Generated by Django 3.1.8 on 2021-05-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0002_custom_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldenconfigsettings",
            name="exclude_chassis_members",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="goldenconfigsettings",
            name="only_primary_ip",
            field=models.BooleanField(default=False),
        ),
    ]
