# Generated by Django 3.1.7 on 2021-04-14 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0004_initial_part_4'),
        ('nautobot_golden_config', '0003_goldenconfiglinesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfigLineRemove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('regex_line', models.CharField(max_length=200)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_line_remove', to='dcim.platform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackupConfigLineReplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('substitute_text', models.CharField(max_length=200)),
                ('replaced_text', models.CharField(max_length=200)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_line_replace', to='dcim.platform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GoldenConfigLineSettings',
        ),
    ]
