# Generated by Django 3.1.13 on 2021-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_golden_config', '0004_auto_20210616_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcompliance',
            name='actual',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='configcompliance',
            name='extra',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='configcompliance',
            name='intended',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='configcompliance',
            name='missing',
            field=models.JSONField(blank=True),
        ),
    ]
