# Generated by Django 3.1.13 on 2021-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_golden_config', '0005_auto_20210826_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerule',
            name='match_config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
