# Generated by Django 3.1.7 on 2021-04-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0006_backupconfiglinereplace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goldenconfigsettings",
            name="remove_lines",
        ),
        migrations.RemoveField(
            model_name="goldenconfigsettings",
            name="substitute_lines",
        ),
    ]
