# Generated by Django 3.1.13 on 2021-12-07 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0007_multi_repo_support_convert_many"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goldenconfigsetting",
            options={"verbose_name": "Golden Config Setting"},
        ),
        migrations.RemoveField(
            model_name="goldenconfigsetting",
            name="backup_repositories",
        ),
        migrations.RemoveField(
            model_name="goldenconfigsetting",
            name="intended_repositories",
        ),
    ]
