# Generated by Django 3.1.13 on 2021-12-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0013_default_fallback_value_computedfield'),
        ('nautobot_golden_config', '0007_data_retention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldenconfigsetting',
            options={'verbose_name': 'Golden Config Setting'},
        ),
        migrations.AddField(
            model_name='goldenconfigsetting',
            name='backup_repository_template',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='goldenconfigsetting',
            name='intended_repository_template',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='goldenconfigsetting',
            name='backup_repository',
        ),
        migrations.AddField(
            model_name='goldenconfigsetting',
            name='backup_repository',
            field=models.ManyToManyField(blank=True, limit_choices_to={'provided_contents__contains': 'nautobot_golden_config.backupconfigs'}, related_name='backup_repository', to='extras.GitRepository'),
        ),
        migrations.RemoveField(
            model_name='goldenconfigsetting',
            name='intended_repository',
        ),
        migrations.AddField(
            model_name='goldenconfigsetting',
            name='intended_repository',
            field=models.ManyToManyField(blank=True, limit_choices_to={'provided_contents__contains': 'nautobot_golden_config.intendedconfigs'}, related_name='intended_repository', to='extras.GitRepository'),
        ),
    ]
