# Generated by Django 3.1.13 on 2021-12-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_golden_config', '0009_data_retention_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldenconfigsetting',
            name='backup_repositories',
        ),
        migrations.RemoveField(
            model_name='goldenconfigsetting',
            name='intended_repositories',
        ),
    ]
