# Generated by Django 3.2.14 on 2022-07-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0018_convert_sotagg_queries_part5"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="dynamic_group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="golden_config_setting",
                to="extras.dynamicgroup",
            ),
        ),
    ]
