# Generated by Django 3.2.14 on 2022-07-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_golden_config", "0020_convert_dynamicgroup_part_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goldenconfigsetting",
            name="scope",
        ),
    ]
