# Generated by Django 3.2.15 on 2023-04-05 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0021_convert_dynamicgroup_part_3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configcompliance",
            options={"ordering": ["device", "rule"]},
        ),
    ]
