# Generated by Django 3.2.15 on 2023-03-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0021_convert_dynamicgroup_part_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldenconfig",
            name="remediation",
            field=models.TextField(blank=True),
        ),
    ]
