# Generated by Django 3.2.15 on 2023-05-04 10:12

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.mixins
import nautobot_golden_config.models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0014_location_status_data_migration'),
        ('extras', '0047_enforce_custom_field_slug'),
        ('nautobot_golden_config', '0022_goldenconfig_remediation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HConfigOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('hier_options', models.JSONField(default=dict)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('target_platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hconfigoptions', to='dcim.platform')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.AddField(
            model_name='goldenconfig',
            name='remediation_settings',
            field=models.ForeignKey(default=nautobot_golden_config.models.get_default_hconfig_options_id, on_delete=django.db.models.deletion.SET_DEFAULT, to='nautobot_golden_config.hconfigoptions'),
        ),
    ]
