# Generated by Django 3.2.15 on 2023-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0022_alter_configcompliance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancerule",
            name="custom_compliance",
            field=models.BooleanField(default=False),
        ),
    ]
