# Generated by Django 3.2.20 on 2023-09-12 03:52

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
import taggit.managers
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0023_interface_redundancy_group_data_migration"),
        ("extras", "0058_jobresult_add_time_status_idxs"),
        ("nautobot_golden_config", "0024_convert_custom_compliance_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancerule",
            name="config_remediation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configcompliance",
            name="remediation",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RemediationSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("remediation_type", models.CharField(default="hierconfig", max_length=50)),
                ("remediation_options", models.JSONField(blank=True, default=dict)),
                (
                    "platform",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_settings",
                        to="dcim.platform",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ("platform", "remediation_type"),
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),
        migrations.CreateModel(
            name="ConfigPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("plan_type", models.CharField(max_length=20)),
                ("config_set", models.TextField()),
                ("change_control_id", models.CharField(blank=True, max_length=50)),
                ("change_control_url", models.URLField(blank=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="config_plan", to="dcim.device"
                    ),
                ),
                (
                    "feature",
                    models.ManyToManyField(
                        blank=True, related_name="config_plan", to="nautobot_golden_config.ComplianceFeature"
                    ),
                ),
                (
                    "job_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="config_plan", to="extras.jobresult"
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.status"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ("-created", "device"),
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),
    ]
