# Generated by Django 3.2.20 on 2023-09-16 17:12

import django.db.models.deletion
import nautobot.core.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0028_auto_20230916_1712_part1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancefeature",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="compliancefeature",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="compliancerule",
            name="config_ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="compliancerule",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="compliancerule",
            name="match_config",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compliancerule",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="configcompliance",
            name="compliance",
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="configcompliance",
            name="compliance_int",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="configcompliance",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="configcompliance",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="configcompliance",
            name="remediation",
            field=models.JSONField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="configcompliance",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="configplan",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="configplan",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="configremove",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="configremove",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="configreplace",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="configreplace",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="goldenconfig",
            name="backup_last_attempt_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goldenconfig",
            name="backup_last_success_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goldenconfig",
            name="compliance_last_attempt_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goldenconfig",
            name="compliance_last_success_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goldenconfig",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="goldenconfig",
            name="intended_last_attempt_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goldenconfig",
            name="intended_last_success_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goldenconfig",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="goldenconfigsetting",
            name="backup_repository",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"provided_contents__contains": "nautobot_golden_config.backupconfigs"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="backup_repository",
                to="extras.gitrepository",
            ),
        ),
        migrations.AlterField(
            model_name="goldenconfigsetting",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="goldenconfigsetting",
            name="intended_repository",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"provided_contents__contains": "nautobot_golden_config.intendedconfigs"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intended_repository",
                to="extras.gitrepository",
            ),
        ),
        migrations.AlterField(
            model_name="goldenconfigsetting",
            name="jinja_repository",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"provided_contents__contains": "nautobot_golden_config.jinjatemplate"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jinja_template",
                to="extras.gitrepository",
            ),
        ),
        migrations.AlterField(
            model_name="goldenconfigsetting",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="remediationsetting",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="remediationsetting",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
    ]
