# Generated by Django 3.2.20 on 2023-09-16 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0049_remove_slugs_and_change_device_primary_ip_fields"),
        ("nautobot_golden_config", "0028_auto_20230916_1712_part2"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="configplan",
            unique_together={("plan_type", "device", "created")},
        ),
    ]
