# Generated by Django 3.2.21 on 2023-09-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0049_remove_slugs_and_change_device_primary_ip_fields"),
        ("nautobot_golden_config", "0029_alter_configplan_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldenconfig",
            name="device",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dcim.device"),
        ),
    ]
