# Generated by Django 4.2.17 on 2024-12-19 20:51

from django.db import migrations, models

from nautobot_golden_config.utilities.constant import (
    ENABLE_BACKUP,
    ENABLE_COMPLIANCE,
    ENABLE_DEPLOY,
    ENABLE_INTENDED,
    ENABLE_PLAN,
)


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0030_alter_goldenconfig_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="backup_enabled",
            field=models.BooleanField(default=ENABLE_BACKUP),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="compliance_enabled",
            field=models.BooleanField(default=ENABLE_COMPLIANCE),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="deploy_enabled",
            field=models.BooleanField(default=ENABLE_DEPLOY),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="intended_enabled",
            field=models.BooleanField(default=ENABLE_INTENDED),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="plan_enabled",
            field=models.BooleanField(default=ENABLE_PLAN),
        ),
    ]
