# Generated by Django 4.2.24 on 2025-09-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0030_alter_goldenconfig_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configplan",
            name="change_control_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
