# Generated by Django 4.2.23 on 2025-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_golden_config', '0030_alter_goldenconfig_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenconfigsetting',
            name='enable_backup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goldenconfigsetting',
            name='enable_compliance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goldenconfigsetting',
            name='enable_deploy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goldenconfigsetting',
            name='enable_intended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goldenconfigsetting',
            name='enable_plan',
            field=models.BooleanField(default=True),
        ),
    ]
