# Generated by Django 4.2.29 on 2026-05-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0031_alter_configplan_change_control_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_backup",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_compliance",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_deploy",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_intended",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_plan",
            field=models.BooleanField(default=True),
        ),
    ]
