# Generated by Django 4.2.29 on 2026-04-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0031_alter_configplan_change_control_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configcompliance",
            name="compliance_int",
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="empty_compliance_behavior",
            field=models.CharField(default="validated", max_length=20),
        ),
        migrations.AlterField(
            model_name="configcompliance",
            name="compliance",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
