# Generated by Django 5.2.14 on 2026-05-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_golden_config", "0031_alter_configplan_change_control_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_backup",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_compliance",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_deploy",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_intended",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_plan",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_postprocessing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="enable_sotagg",
            field=models.BooleanField(default=True),
        ),
    ]
